### ISSUE TITLE
"enum PointInPolygonResult" has a bug,INSIDE(true)  and  OUTSIDE(false)，so their positions should be exchanged

### ISSUE THREAD

**Issue by klaoli** [kallaballa/nestcpp#2]
enum PointInPolygonResult {
	INSIDE,
	OUTSIDE,
	INVALID};
 -> enum PointInPolygonResult {
	 OUTSIDE,    
         INSIDE,
	 INVALID};

**Comment by kallaballa** [comment]
I abandoned this project in favor of libnfporb
